### ISSUE TITLE
Semi-BUG: Reference of the XML DTD is missing

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#13]
Hi @wirbel-at-vdr-portal ,

Inside the XML output the address of the DTD is missing:
```
<?xml version="1.0" ?>
<!DOCTYPE service_list SYSTEM "https://gen2vdr.de/wirbel/w_scan/dtd/service_list.dtd">

<!-- NOTE:
     if reading or writing w_scan XML file format:
        - please validate XML against DTD above.
        - indent each XML element
        - indent using three spaces, don't use <TAB> char to indent.
        - conform to requirements mentionend in DTD file.
 -->
```

Therefore, I recommend that you add the DTD file to the project source. And if you consider it acceptable, change the URL to the Github raw address. With this change the file will continue to be valid in the future.

And to improve the compatibility, remove the last space in the first line. It will be preferable to use: `<?xml version="1.0"?>`
Regards.

**Comment by wirbel-at-vdr-portal** [comment]
I was not aware that someone else uses this format at all.

It was lost with the transition from w_scan to w_scan_cpp probably long time ago.

**Comment by lars18th** [comment]
> I was not aware that someone else uses this format at all.

I want to use it as a _neutral_ interchange format to ingest data into other tools. That's the reason to fix the bugs related to it and to expand the tool.
 
> It was lost with the transition from w_scan to w_scan_cpp probably long time ago.

Thank you for the last commits.
We can close then the issue?

**Comment by wirbel-at-vdr-portal** [comment]
Yes. There's also a new example file in doc.

**Comment by wirbel-at-vdr-portal** [comment]
done.
