### ISSUE TITLE
Multiple output format at the same time

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#14]
Hi @wirbel-at-vdr-portal ,

Any reason to not support multiple file outputs at the same time? The scanning time is long (between 10~20min.) and when doing some tests it will be useful to _export_ in multiple formats. For example, I want to get XML, VLC-satip and DVB-Viewer at the same time.

Any idea to achieve this?
Thank you.

**Comment by wirbel-at-vdr-portal** [comment]
I don't like this idea.
