### ISSUE TITLE
BUG: SATIP output in the generated output file

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#16]
Hi @wirbel-at-vdr-portal ,

When using SAT>IP tuners the output file includes some debug header with tuner messages. Example:
```
./w_scan_cpp -ft -c DE --satip --satip-server '192.168.1.44:554|DVBT2-1|MySvr:0x08' -V > ./scan.m3u
```

Then at the start of the `scan.m3u` file you will get:
```
SATIP: Adding server '192.168.1.44|DVBT2-1|MySvr' Bind: default Filters: none CI: no Quirks: RtpOverTcp
SATIP: Creating device CardIndex=0 DeviceNumber=0 [device 0]
SATIP: Creating device CardIndex=1 DeviceNumber=1 [device 1]
SATIP: Detected 1 RTP packet error [device 0]
SATIP: Detected 16 RTP packet errors [device 0]
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/" xmlns:vlc="http://www.videolan.org/vlc/playlist/ns/0/">
   <title>DVB Playlist</title>
   <creator>w_scan_cpp</creator>
   <info>https://gen2vdr.de/wirbel/w_scan_cpp/index2.html</info>
   <trackList>
[...]
```

So please remove these `SATIP` lines from the beginning.
Thank you.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

I've isolated the problem to this lines of the `vdr-plugin-satip` plugin:
https://github.com/wirbel-at-vdr-portal/vdr-plugin-satip/blob/12575f4d0039761ec284e3a5d8119de25ddf0e5d/log.h#L12-L17

The problem is that the plugin is printing to the STDOUT instead of the STDERR that is used in the tool. Therefore, I request if you can do some change to solve this.

Thank you.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

This simple patch seems to solve the problem:
```cpp
#include "config.h"

-#define _E_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else esyslog(x); }
-#define _I_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else isyslog(x); }
-#define _D_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else dsyslog(x); }
+#define _E_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else esyslog(x); }
+#define _I_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else isyslog(x); }
+#define _D_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else dsyslog(x); }

#define error(x...)   _E_("SATIP-ERROR: " x)
#define info(x...)    _I_("SATIP: " x)
```

So please consider to merge it.
Regards.

**Comment by wirbel-at-vdr-portal** [comment]
No.

This a new bug, and not a solution.
The setup variable is named **DbgToStdout** and you change it to write to stderr.

**Comment by lars18th** [comment]
Ok. So what solution you suggest to solve the problem? The plugin is writing to the STDOUT and this corrupts the output.
Any idea to solve it?

**Comment by lars18th** [comment]
> The setup variable is named **DbgToStdout** and you change it to write to stderr.

You suggest to create a new configurable variable called **DbgToStderr**, or something else?

Please, comment about it.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

My current idea is something like this:
```cpp
  enum eDebugMode {
    DbgNormal            = 0,
    DbgCallStack         = (1U << 0),
    DbgCurlDataFlow      = (1U << 1),
    DbgDataParsing       = (1U << 2),
    DbgTunerState        = (1U << 3),
    DbgRtspResponse      = (1U << 4),
    DbgRtpPerformance    = (1U << 5),
    DbgRtpPacket         = (1U << 6),
    DbgSectionFiltering  = (1U << 7),
    DbgChannelSwitching  = (1U << 8),
    DbgRtcp              = (1U << 9),
    DbgCommonInterface   = (1U << 10),
    DbgPids              = (1U << 11),
    DbgDiscovery         = (1U << 12),
    DbgReserved1         = (1U << 13),
    DbgToStdout          = (1U << 14),
    DbgCallStackExt      = (1U << 15),
+   DbgToStderr          = (1U << 16),
    DbgModeMask          = 0xFFFF
  };

[...]

#include "config.h"

-#define _E_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else esyslog(x); }
-#define _I_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else isyslog(x); }
-#define _D_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n"); } else dsyslog(x); }
+#define _E_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n") } else if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStderr)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else esyslog(x); }
+#define _I_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n") } else if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStderr)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else isyslog(x); }
+#define _D_(x...) { if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStdout)) { printf(x); printf("\n") } else if (SatipConfig.IsDebugMode(cSatipConfig::DbgToStderr)) { fprintf(stderr,x); fprintf(stderr,"\n"); } else dsyslog(x); }

#define error(x...)   _E_("SATIP-ERROR: " x)
#define info(x...)    _I_("SATIP: " x)
```

And then inside the `w_scan_cpp` tool initialize the satip plugin to use the STDERR.
You agree with that idea?

**Comment by wirbel-at-vdr-portal** [comment]
Sounds reasonable.
But needs a check where SatipConfig is used, if used as a standalone plugin within vdr.
Don't want to break standalone usage.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

I've fixed the problem. It requires two PR:
- Enable 'eDebugMode:DbgToStderr' flag in the plugin: https://github.com/wirbel-at-vdr-portal/vdr-plugin-satip/pull/5
- Initialize accordingly in the tool: https://github.com/wirbel-at-vdr-portal/w_scan_cpp/pull/24

You can see that the changes are simple. Inside the plugin nothing is changed by default. Therefore the current behaviour will continue equal with VDR. And for the tool, if you compile it with an ancient version of the plugin, in this special case the behaviour is that you will not see any debug from SATIP. The reason is because the debug will be '0'. So anyway the problem with the output will also be overcome.

If you agree with these changes, then I'll update the HISTORY.
Regards.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Thank you for merging both patches. 👍 
I close then this issue.
