### ISSUE TITLE
Discussion: "--output-VLC-satip" doesn't include all audio pids

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#18]
Hi @wirbel-at-vdr-portal ,

This is referenced initially in #15, but it's a different question. So, I open a new bug report:

Original comment:
> And another question is how to achieve that all pids are included in the pids= list when using "--output-VLC-satip". In this case, some pids, like the CA PID are missing. It will be desirable to have an option to add all the pids associated to the service in the list.

The problem is that with services with multiple audios, the pid list only includes the first audio track. Futhermore, subtitle pids aren't included. The same for CA pids. And other "non-detected" pids inside the PMT table.

I suggest, to almost fix the code of `PrintVLCsatip()` to include all the pids detected in the lists `APIDs` and `DPIDs` :
https://github.com/wirbel-at-vdr-portal/w_scan_cpp/blob/a7bfaceaf053c1014451d3278a56c1486b642912/OutputFormats.cpp#L1195-L1196

After that you perhaps wants to add the CA pids. And refactor the wirbelscan to include all the pids inside the PMT.

Regards.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

This piece of code partially solves the problem (almost for all current detected pids):
```cpp
     if (c.PMT > 0)           ss << ',' << c.PMT;
     if (c.VPID.PID > 0)      ss << ',' << c.VPID.PID;
     if (c.APIDs.Count() > 0) for (int i=0; i < c.APIDs.Count(); i++)
                              ss << ',' << c.APIDs[i].PID;
     if (c.DPIDs.Count() > 0) for (int i=0; i < c.DPIDs.Count(); i++)
                              ss << ',' << c.DPIDs[i].PID;
     if (c.SPIDs.Count() > 0) for (int i=0; i < c.SPIDs.Count(); i++)
                              ss << ',' << c.SPIDs[i].PID;
     if (c.TPID > 0)          ss << ',' << c.TPID;
```

The code loops over all Audio, Data and Subtitle lists (the `SPIDs` is not in the original code).

I hope you want to merge it.
Regards.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Created another PR (#20) to solve this bug.
Please check it.

After that I've another one patch for the scan plugin to add all (unkown) pids in the SPIDs list. I'm not sure if you want to accept this. However, with a config flag we could enable/disable it. The idea is to provide to the user the alternative of including _ALL_ pids associated with the service. What you think about that?

**Comment by wirbel-at-vdr-portal** [comment]
This is not a bug, i think. The most important audio comes first, as defined in specs.

Unknown PIDs should be clearly **NOT** added, just those which VLC may use to play a channel.

There are many additional pids 'possible' and 'related to the service'. But no-one needs them for VLC.

I'm not even shure, if this is an real improvement, as for example DPIDs will require matching codec supported by the OS - otherwise no sound at all.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

Although you may not want to consider this a bug, it is a true implementation failure. The reason is that VLC has the method to:
- Change audio track.
- Enable/disable subtitles.
- Show Teletext.

Therefore, it doesn't have sense to generate VLC playlist files without all the pids of a service. Why you think will success if you open a service autosetting the audio language if this doesn't correspond to the _first_ audio? Please, reconsider you position. And also take note that the XSPF file format is one standard used by a lot of other a software: https://xspf.org/applications.

**Comment by lars18th** [comment]
Hi, issue closed because it's now fixed.
