### ISSUE TITLE
BUG: Incorrect NIT position calculation

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#22]
Hi @wirbel-at-vdr-portal ,

Antoher bug to fix:
- Sometimes you get the message `NIT: WRONG SATELLITE:`. The cause could be an incorrect calculus because code in the `statemachine.cpp` of the "wirbelscan" plugin. Here the code with the problem patched:
```cpp
                 std::string is_wrong;
                 //if (abs(NitData.transport_streams[i]->OrbitalPos - initial->OrbitalPos) > 5)
                 if (abs(NitData.transport_streams[i]->OrbitalPos) - initial->OrbitalPos > 5)
                    is_wrong = "WRONG SATELLITE ( " + IntToStr(initial->OrbitalPos) + " | " + IntToStr(NitData.transport_streams[i]->OrbitalPos) + " ): ";
                 dlog(0, "NIT: " + is_wrong + "'" + s + "'" + 
                         ", NID = "  + IntToStr(NitData.transport_streams[i]->NID)  +
                         ", ONID = " + IntToStr(NitData.transport_streams[i]->ONID) +
                         ", TID = "  + IntToStr(NitData.transport_streams[i]->TID));
```
As you can see the problem is the incorrect bracket of the `abs()` function. In some cases the value of the `NitData.transport_streams[i]->OrbitalPos` is negative but identical to the value `initial->OrbitalPos`. Therefore what you want to do is get the ABS of the first operand and after compare the offset. Or perhaps you want to ABS both operands and check the difference. In any case I've added the log to print both values to be more easy to understand the problem.

I hope you want to fix this trouble.
Regards.

**Comment by wirbel-at-vdr-portal** [comment]
The bracket is absolutely in correct position. No bug, nothing to fix.
This is a message, that transponder data from a different satellite is found and can be safely ignored.

btw, both number are greater or equal than zero. The line checks, if they are in +/-5 range.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

You're right and my suggestion is wrong. Sorry for it.

However, you can check (using the part of the patch that prints the two values, very useful to see the problem) that when appears the message you can see something like this `-300|300` (please scan i.e. 30W). Therefore this case is _clearly_ a bug.

So here I present an updated version of the code:
```cpp
                 std::string is_wrong;
                 if ( (abs(NitData.transport_streams[i]->OrbitalPos - initial->OrbitalPos) > 5) &&
                      (NitData.transport_streams[i]->OrbitalPos != -(initial->OrbitalPos)) )
                    is_wrong = "WRONG SATELLITE ( " + IntToStr(initial->OrbitalPos) + " | " + IntToStr(NitData.transport_streams[i]->OrbitalPos) + " ): ";
                 dlog(0, "NIT: " + is_wrong + "'" + s + "'" + 
                         ", NID = "  + IntToStr(NitData.transport_streams[i]->NID)  +
                         ", ONID = " + IntToStr(NitData.transport_streams[i]->ONID) +
                         ", TID = "  + IntToStr(NitData.transport_streams[i]->TID));
```
If we name "IP" for `initial->OrbitalPos` and "NP" for `NitData.transport_streams[i]->OrbitalPos` then the changes are:
- The ABS to check the _modulus_ difference (NP - IP) continues equal (as you pointed).
- When the modulus of the difference it's greater than 5, the code checks the edge case of the same value with different sign.
- And finally the error message prints both values.

I hope now you will see the problem and accept the suggestion.
Thank you very much for your very accurate comments and good work in developing this project.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

I've created a PR to _improve_ this. Check it at https://github.com/wirbel-at-vdr-portal/wirbelscan-dev/pull/3/files
I think that I have met all of your requirements to accept the merge.
Regards.
