### ISSUE TITLE
Comment about DVB-T2 PLP support

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/w_scan_cpp#26]
Hi @wirbel-at-vdr-portal ,

This is related to #17 , but I prefer to open a new issue to discuss about this specific question. Here the description of the problem:
- When scanning using DVB-T2 the current behavior searches with different PLP values. First without it (single mode PLP), and after with values 1, 2 and 3. This has the consequence that for each frequency the tool scans four times for each frequency for DVB-T2, and in a second round for DVB-T. Therefore, the scan time could be slow.

Therefore, I have some ideas to improve this behaviour. And I want to commet with you:
- First is if you think it's acceptable to add one parameter to _disable_ the PLP loop. In almost all countries only single PLP mode is used at time. However, the default value could be to use it like now. But with the option to disable it. What you think?
- The second idea is to add another (or the same) parameter to select the PLP range. In fact, the values could range from 1 to 255 (0 is single mode). This is also acceptable?
- The third idea is to change the order of the scan. If DVB-T2 needs more than one test, why not scan first for DVB-T and after for DVB-T2?

I'm only suggesting that you expose your opinion. The reason is to not implement anything non-usable/non-acceptable.
Please comment.
Thank you.

**Comment by lars18th** [comment]
In the meantime, this is the idea that I think is best and simplest:

- Add the parameter `--plp-range N` to the "w_scan_cpp" tool.
- This parameter will range from 0 to 255.
- Value 0 will indicate only simple PLP mode.
- The PLP value will loop from 1 to N.
- And the default value will be '3' that is the current value for DVB-T2 (so by default nothing changes).
- The wirbelscan plugin will be then moddified to accept this parameter in the configuration and will use it.

@wirbel-at-vdr-portal , you agree with that solution?

**Comment by wirbel-at-vdr-portal** [comment]
I want **as less commandline options as reasonable achievable** in this tool.

I don't want _users to control the scan flow_, it's optimized already by me. I don't want users to decide, if they want to scan something specific.

This is a semi-blindscan tool for DTV in software, and if you're blind you don't know all those details anyway. Scanning time is not important here, take your time and be patient.

All of this doesn't fit into here.

**Comment by lars18th** [comment]
Hi @wirbel-at-vdr-portal ,

First of all, thank you for taking the time to respond to my request.

And second, please remember: I'm an engineer and I want to use this tool as an engineer. This tool is unique because: it's command line only; and it works with SAT>IP tuners. This is the reason to communicate with you and to collaborate in what I can.

That said, I don't think it can be illogical if we add something useful that doesn't bother regular users in any way. My suggestions are aimed at _adding_ small things that don't change the _regular_ functionality. And since I don't want to introduce complex code, or harm in any way, that's why I prefer to ask you first. So please consider that my goal here is to _configure_ the scanning process according to my needs. And yes, my needs could not be the same as for regular users. However, I don't believe that an "expert" parameter for setting PLP values can harm anyone. Especially when currently rarely used and when the value may be greater than 3.

From this point, do you have any ideas on the best strategy for setting the PLP value, please?
Thank you.
