### ISSUE TITLE
How do I change the list of transponders?

### ISSUE THREAD

**Issue by ncurado** [wirbel-at-vdr-portal/w_scan_cpp#3]
I'm trying to use w_scan_cpp with a satip server to get a list of channels available through Hispasat. I have it running successfully, but it does not pick up all the channels. I think the issue is that the list of transponders might be incomplete. Does your project use the ones listed in /usr/share/dvb/dvb-s/Hispasat-30.0W or is it from a different list?

**Comment by wirbel-at-vdr-portal** [comment]
The list is part of the tool. Touching this list from users is not foreseen at all.

The base idea is, that such a complete list is never needed or wanted.
Just at least one or two successful hits out of the list to get the NIT from one or two transponders.
The current list is btw from Nov 7, 2021

After that the network information tables from those hits should be sufficient to find almost everything.

If you want to play with transponder lists, you may want to try [https://www.linuxtv.org/wiki/index.php/Dvbv5-scan](https://www.linuxtv.org/wiki/index.php/Dvbv5-scan)

**Comment by ncurado** [comment]
Thanks for the quick reply! I enquired about the transponders because I want to scan an SAT/IP server (minisatip) to create an m3u file; I intend to serve that m3u file from the same server. When I scan using TVHeadEnd, I get more results than with w_scan_cpp. One of the examples of channels not being scanned is Sport TV 6, which is part of transponder 1236000(H;8PSK;27500 3/4;DVB-S2).

**Comment by wirbel-at-vdr-portal** [comment]
Hi,

the description of this git is **"This is my test w_scan_cpp repo. No pull requests/issues/bugs here, use contact given in README."**

Please, don't continue here. github issues is the wrong place for detailled discussions.
If you have further questions or need help, use the contact given in README.

I'm closing this bug now.

**Comment by FlexMcMurphy** [comment]
Hello, I have the exact same problem and would like to ask for help. I checked the Readme of w_scan_cpp which just links back to the website https://www.gen2vdr.de/wirbel/w_scan_cpp/index2.html and on there I can't find anyway to contact someone to ask for help. Can I email you directly perhaps?

**Comment by wirbel-at-vdr-portal** [comment]
You checked the README, but failed to find line #5 of the README?
There's the contact: README line 5.


I you have the same problem as ncurado, then you find the answer in the second field of this thread.
But I you have a different problem, feel free to contact me for discussion.

Anyhow, this is my **test repo** to sync git between a bunch of computers,
the official site you already found.
