### ISSUE TITLE
Compile fails (error: uint16_t has not been declared) with gcc 13.1.1

### ISSUE THREAD

**Issue by M-Reimer** [wirbel-at-vdr-portal/w_scan_cpp#5]
![image](https://github.com/wirbel-at-vdr-portal/w_scan_cpp/assets/3519517/1a89b3f9-1d18-480e-b10f-719b0b964f36)
This is an attempt to build the latest release. I'm sure this worked before but building today always fails with the above error.

**Comment by M-Reimer** [comment]
OK, I could now open a second Issue on your wirbelscan project, but as they are related here, I just add this here:
![image](https://github.com/wirbel-at-vdr-portal/w_scan_cpp/assets/3519517/18820791-4b41-420b-9f3e-17f2fb03e112)
So the root cause is in the wirbelscan plugin source.

**Comment by wirbel-at-vdr-portal** [comment]
Does the latest change in wirbelscan git solve the problem?

**Comment by M-Reimer** [comment]
This change works as a fix for both, vdr-plugin-wirbelscan and w_scan_cpp. I temporarily fixed my Arch PKGBUILDs by applying this commit as a patch.

**Comment by wirbel-at-vdr-portal** [comment]
Ok, bumped/tagged wirbelscan && w_scan_cpp for changes. For details, see diff between tags.
Closing.
